
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("products/new", "Create products")) ?>
</div>

<?php echo $this->tag->form(array("products/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search products</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="type_id">Type</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("type_id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="price">Price</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("price", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="quantity">Quantity</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("quantity", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="status">Status</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("status", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
